export const Hebrew = {
    NavBarSignIn: "הירשם עכשיו",
    NavBarHomePage: "דף הבית",
    NavBarPersonalArea: "אזור אישי",
    NavBarOurShop: "לחנות שלנו",
    NavBarComunityFarmers: "לחקלאי הקהילה שלנו",
    NavBarFaq: "שאלות ותשובות",
    NavBarContactUs: "צור קשר",
    NavBarHello: "שלום",
    RegisterChooseHeader: "אנא בחר/י מה ברצונך להיות",
    RegisterChooseFarmerButton: "חקלאי",
    RegisterChooseGrowerButton: "מגדל",
    WelcomeToPage: "ברוכים הבאים ל",
    FarmerProfile: "פרופיל חקלאי",
    FirstName: "שם פרטי",
    LastName: "שם משפחה",
    Phone: "טלפון",
    Email: "אימייל (שם משתמש)",
    Password: "סיסמה",
    PasswordConfirmation: "אימות סיסמה",
    FarmerLocation: "אזור השטח לגידול",
    FarmerLocationOption1: "מרכז",
    FarmerLocationOption2: "צפון",
    FarmerLocationOption3: "דרום",
    Address: "כתובת",
    FarmerSizeArea: "גודל שטח החממה",
    FarmerAboutMe: "על עצמי",
    FarmerSizeAreaMsg1: "יש להזין את גודל השטח בכפולות של",
    SquareMeter: 'מ"ר',
    FarmerAboutMeMsg: "טקסט זה יופיע כאשר הלקוח יבחר חקלאי",
    EmptyField: "שדה זה אינו יכול להישאר ריק",
    EmailValidationError: "כתובת האימייל שגויה",
    PasswordError: "הסיסמה חייבת להכיל 8 תווים, אות גדולה, אות קטנה ומספר",
    SizeAreaError: "שדה זה אינו יכול להישאר ריק או לא להיות בכפולות שצוינו",
    PasswordConfirmError: "הסיסמאות לא זהות!",
    ExperienceToGrow: "יש לי את התנאים והניסיון לגדל:",
    VegList: "רשימת ירקות לגידול",
    FieldCropList: "רשימת גידולי שדה",
    Approve: "אישור",
    PricingComment: 'מחירי הירקות וגידולי השדה הינם המחירים המומלצים ע"י החנות של Co-Greenhouse וניתנים לשינוי',
    VegPricingComment: 'יש לוודא שלכל ירק מעודכן מחיר',
    IntrestingInFieldCrops: 'אני מעוניין לאפשר רכישת גידולי שדה',
    FieldCropPrice: 'עלות מסלול גידולי שדה תהיה',
    Shekals: 'ש"ח',
    FarmerFieldCropsChoosePlanError: 'יש לבחור תכנית לגידולי שדה או להסיר גידולי שדה נבחרים',
    FarmerFieldCropsPriceError: 'יש לעדכן מחיר לתכנית גידולי שדה',
    FarmerVegPlansError: 'יש לבחור תכנית אחת לפחות',
    FarmerVegPlansPricingError: 'לכל תוכנית נבחרת יש לעדכן מחיר',
    PlanName1: 'מגדל עצמאי',
    PlanName2: 'ביניים',
    PlanName3: 'ליווי שוטף',
    FarmerPlan1: 'במסלול זה אין התערבות של החקלאי',
    FarmerPlan2: 'במסלול זה יש התערבות חלקית של החקלאי',
    FarmerPlan3: 'במסלול זה יש התערבות מלאה של החקלאי',
    FarmerPlanInclude: 'המסלול כולל:',
    FarmerPlanArea: 'שטח של ',
    FarmerPlanWater: 'מים',
    FarmerPlanSupport: 'ייעוץ אישי',
    FarmerPlanCare: 'טיפול מלא בחלקה',
    Approval1: 'קראתי את ',
    Approval2: 'התקנון',
    Approval3: ' ואני מסכים לכל תנאיו',
    FormContinue: 'המשך להזנת אמצעי תשלום',
    VegPricingListItemCost: 'מחיר לשתיל',
    VegPricingListItemTitle: 'מחירי ירקות',
    FieldCropPricingListItemTitle: 'מחירי גידולי שדה'
};

export const English = {
    NavBarSignIn: "Sign In",
    NavBarHomePage: "Home Page",
    NavBarPersonalArea: "Personal Area",
    NavBarOurShop: "Shop",
    NavBarComunityFarmers: "Our Comunity Farmers",
    NavBarFaq: "Faq",
    NavBarContactUs: "Contact Us",
    NavBarHello: "Hello",
    RegisterChooseHeader: "Please choose what you want to be",
    RegisterChooseFarmerButton: "Farmer",
    RegisterChooseGrowerButton: "Grower",
    WelcomeToPage: "Welcome to",
    FarmerProfile: "Farmer profile",
    FirstName: "First name",
    LastName: "Last name",
    Phone: "Phone",
    Email: "Email (user name)",
    Password: "Password",
    PasswordConfirmation: "Confirm password",
    FarmerLocation: "Area for growing",
    FarmerLocationOption1: "Center",
    FarmerLocationOption2: "North",
    FarmerLocationOption3: "south",
    Address: "Address",
    FarmerSizeArea: "The size of the greenhouse area",
    FarmerAboutMe: "About me",
    FarmerSizeAreaMsg1: "You must enter the size of the space in multiples of",
    SquareMeter: 'square meter',
    FarmerAboutMeMsg: "This text will appear when the customer chooses a farmer",
    EmptyField: "This field cannot remain blank",
    EmailValidationError: "The email address is incorrect",
    PasswordError: "The password must contain 8 characters, a upercase letter, a lowercase letter and a number",
    SizeAreaError: "This field cannot remain blank or not to be in the specified Multiples",
    PasswordConfirmError: "The passwords are not the same!",
    ExperienceToGrow: "I have the conditions and the experience to raise:",
    VegList: "List of vegetables for growing",
    FieldCropList: "List of field crops for growing",
    Approve: "Update",
    PricingComment: "The price of vegetables and field crops is recommended by Co-Greenhouse's shop and can be changed",
    VegPricingComment: 'Make sure that each vegetable has an updated price',
    IntrestingInFieldCrops: 'I would like to enable the purchase of field crops',
    FieldCropPrice: "Field crops's plan cost will be",
    Shekals: 'NIS',
    FarmerFieldCropsChoosePlanError: 'Field crops plan must be selected or remove selected field crops',
    FarmerFieldCropsPriceError: 'A price must be updated to the field crops plan',
    FarmerVegPlansError: 'At least one plan must be selected',
    FarmerVegPlansPricingError: 'Each selected program has a price update',
    PlanName1: 'Independent grower',
    PlanName2: 'middle',
    PlanName3: 'Ongoing accompaniment',
    FarmerPlan1: 'There is no intervention of the farmer on this plan',
    FarmerPlan2: 'This plan has a partial involvement of the farmer',
    FarmerPlan3: 'This plan has a full involvement of the farmer',
    FarmerPlanInclude: 'The plan includes:',
    FarmerPlanArea: 'Area of ',
    FarmerPlanWater: 'Water',
    FarmerPlanSupport: 'Personal consultation',
    FarmerPlanCare: 'Full-part care',
    Approval1: 'I have read the ',
    Approval2: 'bylaws',
    Approval3: ' and I agree to all terms',
    FormContinue: 'Continue to enter method of payment',
    VegPricingListItemCost: 'Price per plant',
    VegPricingListItemTitle: 'Vegetable prices',
    FieldCropPricingListItemTitle: 'Field crops Prices'
};