export const Hebrew = {
    NavBarSignIn: "הירשם עכשיו",
    NavBarHomePage: "דף הבית",
    NavBarPersonalArea: "אזור אישי",
    NavBarOurShop: "לחנות שלנו",
    NavBarComunityFarmers: "לחקלאי הקהילה שלנו",
    NavBarFaq: "שאלות ותשובות",
    NavBarContactUs: "צור קשר",
    NavBarHello: "שלום",
    RegisterChooseHeader: "אנא בחר/י מה ברצונך להיות",
    RegisterChooseFarmerButton: "חקלאי",
    RegisterChooseGrowerButton: "מגדל",
    WelcomeToPage: "ברוכים הבאים",
    FarmerProfile: "פרופיל חקלאי",
    FirstName: "שם פרטי",
    LastName: "שם משפחה",
    Phone: "טלפון",
    Email: "אימייל (שם משתמש)",
    Password: "סיסמה",
    PasswordConfirmation: "אימות סיסמה",
    FarmerLocation: "אזור השטח לגידול",
    FarmerLocationOption1: "מרכז",
    FarmerLocationOption2: "צפון",
    FarmerLocationOption3: "דרום",
    Address: "כתובת",
    FarmerSizeArea: 'גודל שטח החממה במ"ר',
    FarmerAboutMe: "על עצמי",
    FarmerSizeAreaMsg1: "יש להזין את גודל השטח בכפולות של",
    SquareMeter: 'מ"ר',
    FarmerAboutMeMsg: "טקסט זה יופיע כאשר הלקוח יבחר חקלאי",
    EmptyField: "שדה זה אינו יכול להישאר ריק",
    EmailValidationError: "כתובת האימייל שגויה",
    PasswordError: "הסיסמה חייבת להכיל 8 תווים, אות גדולה, אות קטנה ומספר",
    SizeAreaError: "שדה זה אינו יכול להישאר ריק או לא להיות בכפולות שצוינו",
    PasswordConfirmError: "הסיסמאות לא זהות!",
    ExperienceToGrow: "יש לי את התנאים והניסיון לגדל:",
    VegList: "רשימת ירקות לגידול",
    FieldCropList: "רשימת גידולי שדה",
    Approve: "אישור",
    PricingComment: 'מחירי הירקות וגידולי השדה הינם המחירים המומלצים ע"י החנות של Co-Greenhouse וניתנים לשינוי',
    VegPricingComment: 'יש לוודא שלכל ירק מעודכן מחיר',
    IntrestingInFieldCrops: 'אני מעוניין לגדל גידולי שדה בנוסף לגידולי החממה',
    FieldCropPrice: 'עלות מסלול גידולי שדה תהיה',
    Shekals: 'ש"ח',
    FarmerFieldCropsChoosePlanError: 'יש לבחור תכנית לגידולי שדה או להסיר גידולי שדה נבחרים',
    FarmerFieldCropsPriceError: 'יש לעדכן מחיר לתכנית גידולי שדה',
    FarmerVegPlansError: 'יש לבחור תכנית אחת לפחות',
    FarmerVegPlansPricingError: 'לכל תוכנית נבחרת יש לעדכן מחיר',
    PlanName1: 'מגדל עצמאי',
    PlanName2: 'ביניים',
    PlanName3: 'ליווי שוטף',
    FarmerPlan1: 'במסלול זה אין התערבות של החקלאי',
    FarmerPlan2: 'במסלול זה יש התערבות חלקית של החקלאי',
    FarmerPlan3: 'במסלול זה יש התערבות מלאה של החקלאי',
    FarmerPlanInclude: 'המסלול כולל:',
    FarmerPlanArea: 'שטח של ',
    FarmerPlanWater: 'מים לגידול שוטף',
    FarmerPlanSupport: 'מפגש ראשוני עם החקלאי הנבחר להיכרות וייעוץ',
    FarmerPlanSupport2: 'מפגש ראשוני עם החקלאי הנבחר להיכרות ותכנון החלקה שלך',
    FarmerPlanCare: 'טיפול מלא של החקלאי בשטח - דואג לחלקה ולגידולים',
    FarmerPlanCommunity: 'גישה לכל ',
    FarmerPlanCommunity2: 'שירותי הקהילה',
    FarmerPlanApointment: 'מפגש אחת לשבועיים עם החקלאי להמשך ליווי, ייעוץ והכוונה',
    FarmerPlanBySeeds: 'אפשרות לקניית שתילים/זרעים מהחנות הקהילתית',
    FarmerPlanBfertilization: 'דישון',
    Approval1: 'קראתי את ',
    Approval2: 'התקנון',
    Approval3: ' ואני מסכים לכל תנאיו',
    FormContinue: 'המשך להזנת אמצעי תשלום',
    VegPricingListItemCost: 'מחיר לשתיל',
    VegPricingListItemTitle: 'מחירי ירקות',
    FieldCropPricingListItemTitle: 'מחירי גידולי שדה',
    PaymentDetailsTitle: 'חשבון בנק לקבלת תשלום',
    PaymentDetailsAccOwner: 'שם בעל החשבון',
    PaymentDetailsAccNumber: 'מספר חשבון בנק',
    PaymentDetailsChooseBank: 'בנק',
    PaymentDetailsBankNumber: 'סניף',
    PaymentDetailsBankName1: 'בנק אגוד',
    PaymentDetailsBankName2: 'בנק אוצר החייל',
    PaymentDetailsBankName3: 'בנק דיסקונט',
    PaymentDetailsBankName4: 'בנק הפועלים',
    PaymentDetailsBankName5: 'בנק לאומי',
    PaymentDetailsBankName6: 'בנק מזרחי',
    PaymentDetailsBankName7: 'הבנק הבינלאומי',
    PaymentCreditCardTitle: 'אמצעי תשלום',
    PaymentCreditCardfullname: 'שם בעל הכרטיס',
    PaymentCreditCardNumber: 'מספר כרטיס האשראי',
    PaymentCreditCardDate: 'תוקף',
    PaymentCreditCardCVV: 'CVV',
    PaymentCreditCardBusniessNumber: 'מספר עוסק מורשה/ח.פ',
    FarmerProfileNameFinalApprove: 'שליחה לאישור סופי',
    SignUpButton: 'הירשם',
    GrowerProfile: 'פרופיל מגדל',
    GrowerChooseOnlyOnePlan: 'בחירת מסלול (יש לבחור מסלול אחד)',
    GrowerSizearea: 'אזור השטח לגידול',
    GrowerChooseAPlanError: 'יש לבחור מסלול',
    GrowerChooseAFarmerError: 'יש לבחור חקלאי',
    GrowerFarmerName: 'שם החקלאי',
    GrowerFarmerAboutMe: 'דבר החקלאי',
    GrowerFarmerVegs: 'גידולים מוצעים',
    GrowerFarmerPlans: 'מסלולים',
    GrowerFarmerReadMore: 'קרא עוד',
    ReadMoreTitle: 'מידע נוסף על החקלאי',
    ReadMoreActiveFarms: 'חלקות פנויות',
    ReadMoreFieldsCropsCostInformation: 'עלות תכנית גידולי שדה (אופציונאלי):',
    ReadMoreFieldsCrops: 'גידולי שדה אפשריים:',
    GrowerShekalsPerMonth: ' ש"ח לחודש',
    GrowerChooseVegHeader: 'אנא בחר\י את הירקות שברצונך לגדל',
    GrowerChooseVegMiniTitle: 'צפי יבול ממוצע לשנה לפי טור גידול',
    GrowerChooseVegWeight: 'ק"ג',
    GrowerChooseVegMoreInformation: 'מידע נוסף',
    GrowerChooseVegHelkaHeader: 'הרכב החלקה לגידולי חממה (לפי טור גידול)',
    GrowerChooseVegFieldHelkaHeader: 'הרכב החלקה לגידולי שדה (לפי טור גידול)',
    GrowerChooseVegPlants: 'שתילים',
    GrowerChooseVegTotalCost: 'עלות כוללת',
    GrowerChooseVegTotalCost2: 'עלות שתילים',
    GrowerFieldCropsPlanApproval: 'אני מעוניין להוסיף מסלול לגידולי שדה',
    GrowerFieldCropsPlanCost: 'עלות מסלול גידולי שדה הינה',
    GrowerAndText: ' וגם ',
    GrowerChooseFieldCropHeader: 'אנא בחר\י את גידולי השדה שברצונך לגדל',
    GrowerTotalBillMonthlyTitle: 'פירוט חשבון לתשלום חודשי',
    GrowerTotalBillMonthlyItem: 'פריט',
    GrowerTotalBillMonthlyItemCost: 'מחיר פריט',
    GrowerTotalBillMonthlyItemAnount: 'כמות',
    GrowerTotalBillMonthlyItemTotal: 'סה"כ',
    GrowerTotalBillItemPaymentType: 'סוג התשלום',
    GrowerTotalBillMonthlyItemPaymentType: 'חודשי',
    GrowerTotalBillOneTimeItemPaymentType: 'חד פעמי',
    GrowerTotalBillOneTimeTitle: 'פירוט חשבון שתילים',
    GrowerTotalBillMonthlyTotalToPay: 'סה"כ לתשלום',
    GrowerTotalBillPlants: 'שתילי',
    GrowerFieldCropsText: 'גידולי שדה',
    GrowerDoubleHelkaErrorText1: 'לגידול הירקות הבאים:',
    GrowerDoubleHelkaErrorText2: 'יש צורך בשני טורי גידול',
    GrowerSubmitMsgText: 'מגדל יקר',
    FarmerSubmitMsgText: 'חקלאי יקר',
    SubmitMsgText2: 'פרטיך נקלטו בהצלחה ונבדקים כעת ע"י Co-GreenHouse',
    SubmitMsgText3: 'נציג ייצור איתך קשר בהקדם',
    SubmutMsgButton: 'חזרה לאזור האישי',
    UpdateProfileMsg: 'פרטיך עודכנו בהצלחה!',
    NumberOfActivePlots: 'מספר חלקות',
    PersonalDetails: 'פרטים אישיים',
    ChangePaymentMethod: 'שינוי פרטים לתשלום חודשי',
    GrowerListTitle: 'לקוחות',
    GrowerListFullName: 'שם מלא',
    GrowerListPhone: 'טלפון',
    GrowerListEmail: 'דואר אלקטרוני',
    GrowerListFourCrops: 'ארבעת הגידולים',
    GrowerListClientActive: 'לקוח פעיל',
    GrowerListPlanActivation: 'תחילת מסלול',
    GrowerListPlan: 'מסלול',
    GrowerListVegDetails : 'גידולי חממה: ',
    GrowerListFieldCropsDetails : 'גידולי שדה: ',
    GrowerListFieldCropsExtra : ' + גידולי שדה',
    FarmerPersonalAreaPlansCost: 'מחירי מסלולים',
    FarmerPersonalAreaFieldCropPlanCost: 'מחיר מסלול גידולי שדה',
    PerMonth: 'לחודש',
    Update: 'עדכון',
    GrowerPurchaseInShop: 'רכישת שתילים מחקלאי',
    GrowerPersonalAreaSubscriptionActivationDate: 'תאריך תחילת מנוי',
    GrowerPersonalAreaChoosenPlan: 'מסלול שנבחר',
    GrowerPersonalAreaChoosenVeg: 'גידולים שנבחרו',
    GrowerPersonalAreaChoosenFieldCrops: 'גידולי שדה שנבחרו',
    GrowerPersonalAreaChoosenFarmer: 'החקלאי שנבחר',
    GrowerPersonalAreaCancelSubButton: 'ביטול מנוי',
    GrowerPersonalAreaCancelSubButtonAreUSure: 'האם אתה בטוח שברצונך לבטל את המנוי?',
    Yes: 'כן',
    No: 'לא',
    GrowerPersonalShopTitle: ' רכישת שתילים מהחקלאי שלי ',
    GrowerPersonalShopAddToBucket: 'הוסף לסל',
    GrowerPersonalShopProductName: 'שם המוצר',
    GrowerPersonalShopProductAmount: 'כמות',
    GrowerPersonalShopProductPrice: 'מחיר',
    GrowerPersonalShopFarmerDetails: 'פרטי החקלאי שלי',
    GrowerPersonalShopBucketEmpty: 'סל הקניות ריק',
    GrowerPersonalShopPurchase: 'לסיום ורכישה',
    GrowerPersonalShopError: 'יש לרכוש לפחות מוצר אחד',
    GrowerPersonalShopTotalToPay: 'סה"כ לתשלום',
    GrowerPersonalShopFarmerEmpty: 'לחקלאי זה אין שתילים למכירה',
    GrowerPersonalShopPurchaseComletedText1: 'הרכישה בוצעה בהצלחה!',
    GrowerPersonalShopPurchaseComletedText2: 'אימייל עם פרטי העסקה ישלח אליך בהקדם',
    GrowerPersonalShopPurchaseComletedText3: 'תודה CO-Greenhouse',
    LoginEmail: 'אימייל',
    LoginTitle: 'כניסה למערכת',
    LoginForgotPassword: 'שכחתי סיסמה',
    LoginConnectButton: 'התחבר',
    ForgotPasswordTitle: 'איפוס סיסמה',
    ForgotPasswordSendButton: 'שלח אימייל לאיפוס סיסמה',
    ForgotPasswordSuccessText: 'במידה וחשבונך קיים במערכת, נשלח לך מייל עם קישור לעדכון סיסמתך',
    UpdatePasswordTitle: 'עדכון סיסמה',
    UpdatePasswordSendButton: 'עדכן סיסמה',
    UpdatePasswordSuccessText: 'סיסמתך נשמרה בהצלחה.',
    UpdateUserNameTitle: 'עדכון שם משתמש / אימייל',
    UpdateUserNameButton: 'עדכן שם משתמש',
    UpdateUserNameAlert: 'בכדי לעדכן שם משתמש עלייך להיות מחובר',
    UpdateUserNameSuccessText: 'שם המשתמש עודכן בהצלחה, אנא התחבר מחדש למערכת',
    CancelSubscriptionMsg: 'המנוי הופסק בהצלחה',
    LogIn: 'התחבר',
    LogOut: 'התנתק',
    PhoneNumberError: 'מספר הטלפון ריק או לא תקין',
    NonActivePlan: 'למנוי זה אין מסלול פעיל',
    FarmerHaveEmptyVegInList: 'יש לבחור לפחות ירק או גידול שדה אחד בתכנית שנבחרה',
    FarmerFieldCropsButtonText: 'גידולי שדה',
    FarmerGreenhouseCropsButtonText: 'גידולי חממה',
    SeasonWarning: 'מיקומי הגידולים וסוגם עשויים להשתנות בין החממה לגידולי שדה בשטח פתוח ע"פ מזג האויר והעונה.'
};

export const English = {
    NavBarSignIn: "Sign Up",
    NavBarHomePage: "Home Page",
    NavBarPersonalArea: "Personal Area",
    NavBarOurShop: "Shop",
    NavBarComunityFarmers: "Our Comunity Farmers",
    NavBarFaq: "Faq",
    NavBarContactUs: "Contact Us",
    NavBarHello: "Hello",
    RegisterChooseHeader: "Please choose what you want to be",
    RegisterChooseFarmerButton: "Farmer",
    RegisterChooseGrowerButton: "Grower",
    WelcomeToPage: "Welcome",
    FarmerProfile: "Farmer profile",
    FirstName: "First name",
    LastName: "Last name",
    Phone: "Phone",
    Email: "Email (user name)",
    Password: "Password",
    PasswordConfirmation: "Confirm password",
    FarmerLocation: "Area for growing",
    FarmerLocationOption1: "Center",
    FarmerLocationOption2: "North",
    FarmerLocationOption3: "south",
    Address: "Address",
    FarmerSizeArea: "The size of the greenhouse area in square meter",
    FarmerAboutMe: "About me",
    FarmerSizeAreaMsg1: "You must enter the size of the space in multiples of",
    SquareMeter: 'square meter',
    FarmerAboutMeMsg: "This text will appear when the customer chooses a farmer",
    EmptyField: "This field cannot remain blank",
    EmailValidationError: "The email address is incorrect",
    PasswordError: "The password must contain 8 characters, a upercase letter, a lowercase letter and a number",
    SizeAreaError: "This field cannot remain blank or not to be in the specified Multiples",
    PasswordConfirmError: "The passwords are not the same!",
    ExperienceToGrow: "I have the conditions and the experience to raise:",
    VegList: "List of vegetables for growing",
    FieldCropList: "List of field crops for growing",
    Approve: "Update",
    PricingComment: "The price of vegetables and field crops is recommended by Co-Greenhouse's shop and can be changed",
    VegPricingComment: 'Make sure that each vegetable has an updated price',
    IntrestingInFieldCrops: 'I am interested in growing field crops in addition to greenhouse crops',
    FieldCropPrice: "Field crops's plan cost will be",
    Shekals: 'NIS',
    FarmerFieldCropsChoosePlanError: 'Field crops plan must be selected or remove selected field crops',
    FarmerFieldCropsPriceError: 'A price must be updated to the field crops plan',
    FarmerVegPlansError: 'At least one plan must be selected',
    FarmerVegPlansPricingError: 'Each selected program has a price update',
    PlanName1: 'Independent grower',
    PlanName2: 'middle',
    PlanName3: 'Ongoing accompaniment',
    FarmerPlan1: 'There is no intervention of the farmer on this plan',
    FarmerPlan2: 'This plan has a partial involvement of the farmer',
    FarmerPlan3: 'This plan has a full involvement of the farmer',
    FarmerPlanInclude: 'The plan includes:',
    FarmerPlanArea: 'Area of ',
    FarmerPlanWater: 'Water for continuous growth',
    FarmerPlanSupport: 'Preliminary meeting with the selected farmer for acquaintance and counseling',
    FarmerPlanSupport2: 'Preliminary meeting with the selected farmer for acquaintance and planning your plot',
    FarmerPlanCare: 'Full treatment of farmer in the field – taking care of the plot and crops',
    FarmerPlanCommunity: 'Access to all ',
    FarmerPlanCommunity2: 'Community services',
    FarmerPlanApointment: 'meeting with the farmer every two weeks for further accompanying counseling and guidance',
    FarmerPlanBySeeds: 'Option to buy seedlings/seeds from the Community store',
    FarmerPlanBfertilization: 'Fertilization',
    Approval1: 'I have read the ',
    Approval2: 'bylaws',
    Approval3: ' and I agree to all terms',
    FormContinue: 'Continue to enter method of payment',
    VegPricingListItemCost: 'Price per plant',
    VegPricingListItemTitle: 'Vegetable prices',
    FieldCropPricingListItemTitle: 'Field crops Prices',
    PaymentDetailsTitle: 'Bank account for receiving payment',
    PaymentDetailsAccOwner: 'Name of the account holder',
    PaymentDetailsAccNumber: 'Bank account Number',
    PaymentDetailsChooseBank: 'Bank',
    PaymentDetailsBankNumber: 'Branch',
    PaymentDetailsBankName1: 'Union Bank of Israel',
    PaymentDetailsBankName2: 'Bank Otsar Ha-Hayal',
    PaymentDetailsBankName3: 'Israel Discount Bank',
    PaymentDetailsBankName4: 'Bank Hapoalim',
    PaymentDetailsBankName5: 'Bank Leumi',
    PaymentDetailsBankName6: 'Bank Mizrahi-Tefahot',
    PaymentDetailsBankName7: 'First International Bank of Israel',
    PaymentCreditCardTitle: 'method of payment',
    PaymentCreditCardfullname: "Cardholder's name",
    PaymentCreditCardNumber: 'Credit card number',
    PaymentCreditCardDate: 'validity',
    PaymentCreditCardCVV: 'CVV',
    PaymentCreditCardBusniessNumber: 'Licensed dealer/private company number',
    FarmerProfileNameFinalApprove: 'Send for final approval',
    SignUpButton: 'Sign Up',
    GrowerProfile: 'Grower profile',
    GrowerChooseOnlyOnePlan: 'Select a plan (one plan must be selected)',
    GrowerSizearea: 'Area for growing',
    GrowerChooseAPlanError: 'A plan must be chosen.',
    GrowerChooseAFarmerError: 'A farmer must be chosen.',
    GrowerFarmerName: 'Farmer Name',
    GrowerFarmerAboutMe: 'About me',
    GrowerFarmerVegs: 'Suggested crops',
    GrowerFarmerPlans: 'Plans',
    GrowerFarmerReadMore: 'Read more',
    ReadMoreTitle: 'More information about the farmer',
    ReadMoreActiveFarms: 'Available plot of land',
    ReadMoreFieldsCropsCostInformation: 'Crops plan cost (optional)',
    ReadMoreFieldsCrops: 'Possible field crops:',
    GrowerShekalsPerMonth: ' shekals per month',
    GrowerChooseVegHeader: 'Please choose the vegetables you want to grow',
    GrowerChooseVegMiniTitle: 'Average yield per year in a growth column',
    GrowerChooseVegWeight: 'kilogram',
    GrowerChooseVegMoreInformation: 'Additional Information',
    GrowerChooseVegHelkaHeader: 'Plot composition for greenhouse crops (according to the growth column)',
    GrowerChooseVegFieldHelkaHeader: 'Plot composition for field crops (according to the growth column)',
    GrowerChooseVegPlants: 'seedlings',
    GrowerChooseVegTotalCost: 'Total cost',
    GrowerChooseVegTotalCost2: 'Seedlings cost',
    GrowerFieldCropsPlanApproval: "I'm interested in acquiring a plan for field crops",
    GrowerFieldCropsPlanCost: 'Field crops cost is',
    GrowerAndText: ' and ',
    GrowerChooseFieldCropHeader: 'Please choose the field crops you want to grow',
    GrowerTotalBillMonthlyTitle: 'Details of a monthly payment',
    GrowerTotalBillMonthlyItem: 'Item',
    GrowerTotalBillMonthlyItemCost: 'Item price',
    GrowerTotalBillMonthlyItemAnount: 'quantity',
    GrowerTotalBillMonthlyItemTotal: 'Total',
    GrowerTotalBillMonthlyItemPaymentType: 'Monthly',
    GrowerTotalBillOneTimeItemPaymentType: 'one-time',
    GrowerTotalBillOneTimeTitle: 'Details of a seedlings payment',
    GrowerTotalBillMonthlyTotalToPay: 'Total charge',
    GrowerTotalBillPlants: 'seedling',
    GrowerTotalBillItemPaymentType: 'Payment method',
    GrowerFieldCropsText: 'Field crops',
    GrowerDoubleHelkaErrorText1: 'For growing the following vegetables:',
    GrowerDoubleHelkaErrorText2: 'two crops columns are needed',
    GrowerSubmitMsgText: 'Dear grower',
    FarmerSubmitMsgText: 'Dear farmer',
    SubmitMsgText2: 'Your details have been successfully received and are now being tested by Co-GreenHouse',
    SubmitMsgText3: 'Representative will contact you shortly',
    SubmutMsgButton: 'Back to Personal area',
    UpdateProfileMsg: 'Your details have been updated successfully',
    NumberOfActivePlots: 'Number of plots',
    PersonalDetails: 'Personal details',
    ChangePaymentMethod: 'Change details for monthly payment',
    GrowerListTitle: 'Clients',
    GrowerListFullName: 'Full name',
    GrowerListPhone: 'phone',
    GrowerListEmail: 'Email',
    GrowerListFourCrops: 'Four crops',
    GrowerListClientActive: 'Active',
    GrowerListPlanActivation: 'Plan Activation',
    GrowerListPlan: 'Plan',
    GrowerListVegDetails : 'Greenhouse crops: ',
    GrowerListFieldCropsDetails : 'Field crops: ',
    GrowerListFieldCropsExtra : ' + Field crops',
    FarmerPersonalAreaPlansCost: 'Plans cost',
    FarmerPersonalAreaFieldCropPlanCost: 'Field crop plan cost',
    PerMonth: 'Per month',
    Update: 'Update',
    GrowerPurchaseInShop: 'Purchase seedlings from farmer',
    GrowerPersonalAreaSubscriptionActivationDate: 'Subscription start date',
    GrowerPersonalAreaChoosenPlan: 'Selected plan',
    GrowerPersonalAreaChoosenVeg: 'Selected greenhouse crops',
    GrowerPersonalAreaChoosenFieldCrops: 'Selected field crops',
    GrowerPersonalAreaChoosenFarmer: 'The selected farmer',
    GrowerPersonalAreaCancelSubButton: 'Cancel subscription',
    GrowerPersonalAreaCancelSubButtonAreUSure: 'Are you sure you want to Cancel the subscription?',
    Yes: 'Yes',
    No: 'No',
    GrowerPersonalShopTitle: ' purchase seedlings from my own Farmer ',
    GrowerPersonalShopAddToBucket: 'Add to Cart',
    GrowerPersonalShopProductName: 'Product Name',
    GrowerPersonalShopProductAmount: 'Amount',
    GrowerPersonalShopProductPrice: 'Price',
    GrowerPersonalShopFarmerDetails: 'My Farmer details',
    GrowerPersonalShopBucketEmpty: 'The shopping cart is empty.',
    GrowerPersonalShopPurchase: 'Finish and purchase',
    GrowerPersonalShopError: 'At least one product must be purchased',
    GrowerPersonalShopTotalToPay: 'Total charge',
    GrowerPersonalShopFarmerEmpty: 'This farmer has no seedlings for sale',
    GrowerPersonalShopPurchaseComletedText1: 'Purchase successfully!',
    GrowerPersonalShopPurchaseComletedText2: 'An email with the details of the transaction will be sent to you shortly.',
    GrowerPersonalShopPurchaseComletedText3: 'Thank you CO-Greenhouse',
    LoginEmail: 'Email',
    LoginTitle: 'Login',
    LoginForgotPassword: 'Forgot password',
    LoginConnectButton: 'Login',
    ForgotPasswordTitle: 'Password reset',
    ForgotPasswordSendButton: 'Send email password reset',
    ForgotPasswordSuccessText: 'If your account exists in the system we will send you an email with a link to update your password',
    UpdatePasswordTitle: 'Update password',
    UpdatePasswordSendButton: 'Update password',
    UpdatePasswordSuccessText: 'Password was saved successfully.',
    UpdateUserNameTitle: 'Updating a user name/Email',
    UpdateUserNameButton: 'Update User Name',
    UpdateUserNameAlert: 'To update a user name you must be logged on',
    UpdateUserNameSuccessText: 'User name updated successfully please re-connect to the system',
    CancelSubscriptionMsg: 'Subscription terminated successfully',
    LogIn: 'Log In',
    LogOut: 'Log Out',
    PhoneNumberError: 'Phone number is empty or invalid',
    NonActivePlan: 'This subscription has no active plan',
    FarmerHaveEmptyVegInList: 'You must select at least one vegetable or field crop in the selected plan',
    FarmerFieldCropsButtonText: 'Field crops',
    FarmerGreenhouseCropsButtonText: 'Greenhouse crops',
    SeasonWarning: 'Crop locations and thier type may vary between greenhouses and field crops in the open according to the weather and the season'
};